#! /usr/bin/env bash
set -e

function send_job() 
{
  job=$1
  echo "sending job $job"
  jobid=$(uuidgen)

  aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/297794765570/steve-jobs --message-body "$(cat <<EOF
{ "job": "$jobid",
  "job_impl": "00cdf625-70b1-4096-9114-fbe04b6d21ff",
  "input": [ { "url": "s3://steve-jobs/data/crate/mdo/20140503/$job/sku" }, { "url": "s3://steve-jobs/data/crate/mdo/20140503/to_mdo_engine_20140503.tgz" } ],
  "output": "s3://steve-jobs/jobs/$jobid/out"
}
EOF
)"
echo "$job,$jobid" >> sent
}

export -f send_job
cat jobs | parallel -j 20 send_job

