#! /usr/bin/env bash
set -e

function send_job() 
{
  job=$1
  echo "sending job $job"
  jobid=$(uuidgen)

  aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/297794765570/steve-jobs --message-body "$(cat <<EOF
{ "job": "$jobid",
  "job_impl": "c9d0755d-ce7f-4ed5-b66c-c2feee93504b",
  "input": ["s3://steve-jobs/data/crate/mdo/20140412/$job/data_input/", "s3://steve-jobs/data/crate/mdo/20140412/common_input/"],
  "output": "s3://steve-jobs/jobs/$jobid/out"
}
EOF
)"
}

export -f send_job
cat jobs | parallel -j 20 send_job

