#!/usr/bin/env bash

prefix=$(readlink -f $(dirname $BASH_SOURCE)/..)
cp=$prefix/lib/java/\*

# Need to set LB_WEBSERVER_HOME to prefix to allow bloxweb config to find default config
export LB_WEBSERVER_HOME=$prefix

export LB_DEPLOYMENT_HOME=${LB_DEPLOYMENT_HOME:=$HOME}
mkdir -p $LB_DEPLOYMENT_HOME/logs/current

exec java $JAVA_ARGS -cp "$cp" com.logicblox.steve.Main $@
