#! /usr/bin/env bash
set -e

for job in $(tail -n +2 crate_jobs_full.csv | grep -v 4xlarge | cut -d, -f1); do
  echo "sending job $job"
  jobid=$(uuidgen)
  aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/297794765570/steve-jobs --message-body "$(cat <<EOF
{ "job": "$jobid",
  "job_impl": "1cb4233f-e033-4f7f-9814-6bba06b3c16c",
  "input": ["s3://steve-jobs/data/crate/forecast/20140303/$job/data_input/", "s3://steve-jobs/data/crate/forecast/20140303/common_input/"],
  "output": "s3://steve-jobs/jobs/$jobid/out"
}
EOF
)"
done
