package frontend_database_proto;

import "blox/options.proto";

/**
 * ENVELOPES
 */

//
// These look like unions but they are just a message that contain repeated
// fields of the actual request. Services will look for specific request 
// messages only (e.g. the create_job service will only inspect CreateJobRequest
// messages).
//

message RequestEnvelope
{
  repeated CreateJobRequest create_job = 1;
  repeated AddStatusRequest add_status = 2;
  repeated GetStatusRequest get_status = 3;
  repeated SetResultRequest set_result = 4;
  repeated GetResultRequest get_result = 5;

  repeated SetJobImplRequest set_impl = 6;
  repeated GetJobImplRequest get_impl = 7;
}

//
// Services respond with an envelope with multiple Reponses. The order of the response
// messages is guaranteed to be the corresponding order to the request envelope.
//
message ResponseEnvelope
{
  repeated Response response = 1;
}

//
// Services may respond with either errors or messages representing success.
//
message Response
{
  // XOR
  optional Error error = 1;
  optional Job job = 2;
  optional JobImpl impl = 3;
}  

//
// RESPONSE MESSAGES
//

message Error
{
  required string code = 1;
  required string message = 2;
}

message Job
{
  required string id = 1;
  repeated Status status = 2 [(blox.options.set) = true];
}

message JobImpl
{
  required string id = 1;
}


//
// REQUESTS ON JOBS (response contains Job messages) 
//

message CreateJobRequest
{
  required string job_id = 1;
  required string client_id = 2;
  required string impl_id = 3;
  required string output_prefix = 4;
  required string user_id = 5;
  repeated File input = 6 [(blox.options.set) = true];
  repeated Param metadata = 7 [(blox.options.set) = true];
}

message AddStatusRequest
{
  required string job_id = 1;
  required Status status = 2;
}

message GetStatusRequest
{
  required string job_id = 1;
}

message SetResultRequest
{
  required string job_id = 1;
  repeated File output = 2 [(blox.options.set) = true];
}

message GetResultRequest
{
  required string job_id = 1; 
}



//
// REQUESTS ON JOB IMPLEMENTATIONS (response contains JobJobImpl messages) 
//

message SetJobImplRequest
{

}

message GetJobImplRequest
{

}


//
// HELPER MESSAGES
//

message Param
{
  required string key = 1;
  required string value = 2;
}

message File
{
  required string url = 1;
  optional string hash = 2;
}

message Status
{  
  required int64  timestamp = 1;
  required string event     = 2;
  required string machine   = 3;
  required string message   = 4;
}