#! /bin/sh
set -e

lb create trivial_gurobi --lib BloxOptimize,Gurobi5Plugin --overwrite
lb addblock trivial_gurobi --file trivial.logic 
lb print trivial_gurobi x > $2/x.txt
lb print trivial_gurobi y > $2/y.txt
