package com.logicblox.steve.db;

import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.SortedSet;
import java.util.TreeSet;

import com.google.common.collect.ImmutableList;
import com.logicblox.steve.common.Data;
import com.logicblox.steve.common.Status;

/**
 * A representation of the life-cycle of a job.
 * <p/>
 * Most of this class is immutable (the data that comes when creating the job), but parts of it are
 * inherently mutable (outputs and status changes).
 */
public final class Job {

  /**
   * Unique id of the job itself, generated by the frontend.
   */
  public final String id;

  /**
   * Unique id generated by the client requesting the job.
   */
  public final String clientId;

  /**
   * User id of the user who created the job.
   */
  public final String userId;

  /**
   * Account id to which job belongs.
   */
  public final String accountId;

  /**
   * The prefix of the path where to store the results of the job execution.
   */
  public final String outputPrefix;

  /**
   * The public key to use for encrypting results of the job execution.
   */
  public final String outputEncryptionKey;

  /**
   * The id of the job implementation. This is only unique within the account of the user that
   * requested the job.
   */
  public final String jobImplId;

  /**
   * Key/value metadata pairs.
   */
  public final Map<String, String> metadata;

  /**
   * Input archives for the job execution.
   */
  public final Collection<Data> inputData;

  /**
   * Location of the archive of the job implementation.
   */
  public final String jobImplArchive;


  /**
   * Resource usage of job
   */
  public final long cpuUsage;
  public final long maxMemory;
  public final long maxDiskUsage;

  // mutable state

  /**
   * Output archives, generated by the job execution.
   */
  private final Collection<Data> _outputData = new HashSet<Data>();

  /**
   * Ordered collection of status objects, which represent events that occurred in this job.
   */
  private final SortedSet<Status> _status = new TreeSet<Status>(new Comparator<Status>() {

    @Override
    public int compare(Status o1, Status o2) {
      return o1.timestamp.compareTo(o2.timestamp);
    }

  });

  /**
   * Constructor with the immutable state.
   *
   * @param jobId
   * @param clientId
   * @param outputPrefix
   * @param outputEncryptionKey
   * @param jobImplId
   * @param metadata
   * @param inputData
   * @param jobImplArchive
   */
  public Job(String jobId,
             String userId,
             String accountId,
             String clientId,
             String outputPrefix,
             String outputEncryptionKey,
             String jobImplId,
             Map<String, String> metadata,
             Collection<Data> inputData,
             String jobImplArchive,
             long cpuUsage,
             long maxMemory,
             long maxDiskUsage) {

    this.id = jobId;
    this.userId = userId;
    this.accountId = accountId;
    this.clientId = clientId;
    this.outputPrefix = outputPrefix;
    this.outputEncryptionKey = outputEncryptionKey;
    this.jobImplId = jobImplId;
    this.jobImplArchive = jobImplArchive;
    // because strings and Data are immutable, it is safe to just wrap around unmodifiables.
    this.metadata = Collections.unmodifiableMap(metadata);
    this.inputData = Collections.unmodifiableCollection(inputData);
    this.cpuUsage = cpuUsage;
    this.maxMemory = maxMemory;
    this.maxDiskUsage = maxDiskUsage;
  }

  /**
   * Constructor with the immutable and mutable state.
   *
   * @param jobId
   * @param clientId
   * @param outputPrefix
   * @param outputEncryptionKey
   * @param jobImplId
   * @param metadata
   * @param inputData
   * @param jobImplArchive
   * @param outputData
   * @param status
   */
  public Job(String jobId,
             String userId,
             String accountId,
             String clientId,
             String outputPrefix,
             String outputEncryptionKey,
             String jobImplId,
             Map<String, String> metadata,
             Collection<Data> inputData,
             String jobImplArchive,
             long cpuUsage,
             long maxMemory,
             long maxDiskUsage,
             Collection<Data> outputData,
             List<Status> status) {
    this(jobId, userId, accountId, clientId, outputPrefix, outputEncryptionKey, jobImplId, metadata, inputData, jobImplArchive, cpuUsage, maxMemory, maxDiskUsage);
    this._outputData.addAll(outputData);
    this._status.addAll(status);
  }


  synchronized void addStatus(Status status) {
    // Note: this method is only to be used by internal database methods
    _status.add(status);
  }

  synchronized void addOutputData(Collection<Data> output) {
    // Note: this method is only to be used by internal database methods
    _outputData.addAll(output);
  }

  public synchronized List<Status> getStatus() {
    // status is immutable, but we need to protect the status list from changes
    return ImmutableList.copyOf(_status);
  }

  public synchronized Collection<Data> getOutputData() {
    // Data is immutable, but we need to protect the status list from changes
    return Collections.unmodifiableCollection(_outputData);
  }

  public boolean isSucceeded() {
    return hasEvent(Status.Event.SUCCEEDED);
  }

  public boolean isFailed() {
    return hasEvent(Status.Event.FAILED);
  }

  public boolean hasEvent(Status.Event event) {
    for (Status st : _status)
      if (st.event == event)
        return true;

    return false;
  }
}
