#! /usr/bin/env bash
set -e

function send_noop() 
{
  echo "sending job $1"
  jobid=$(uuidgen)
  aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/297794765570/steve-jobs --message-body "$(cat <<EOF
{ "job": "$jobid",
  "job_impl": "c9657b5f-d50d-490f-9566-7179eda380cf",
  "inputs": ["s3://steve-jobs/data/noop/"],
  "output": "s3://steve-jobs/jobs/3aa453bb-2711-4b13-84de-98d1ea4c15a7/out"
}
EOF
)"
}

export -f send_noop
seq 1 $1 | parallel -j 40 send_noop
