package lb.steve.database;

option java_package = "com.logicblox.steve.protocol";
import "blox/options.proto";

/**
 * ENVELOPES
 */

//
// These look like unions but they are just a message that contain repeated
// fields of the actual request. Services will look for specific request 
// messages only (e.g. the create_job service will only inspect CreateJobRequest
// messages).
//

message RequestEnvelope
{
  repeated CreateJobRequest create_job = 1;
  repeated GetJobRequest get_job = 2;
  repeated AddStatusRequest add_status = 3;
  repeated SetResultRequest set_result = 4;

  repeated SetJobImplRequest set_impl = 5;
  repeated GetJobImplRequest get_impl = 6;
}

//
// Services respond with an envelope with multiple Reponses. The order of the response
// messages is guaranteed to be the corresponding order to the request envelope.
//
message ResponseEnvelope
{
  repeated Response response = 1;
}

//
// Services may respond with either errors or messages representing success.
//
message Response
{
  // XOR

  // if an error ocurred in the execution (most operations return an empty response on success)
  optional Error error = 1;

  // only used for CreateJobRequest; the id of the newly created job, or a reused one
  optional string job_id = 2;

  // for GetJobRequest
  optional Job job = 3;

  // for GetJobImplRequest
  repeated JobImpl impl = 4 [(blox.options.set) = true];
}  

//
// RESPONSE MESSAGES
//

message Error
{
  required string code = 1;
  required string message = 2;
}

message Job
{
  required string id = 1;
  required string client_id = 2;
  required string impl_id = 3;
  required string output_prefix = 4;
  required string user_id = 5;
  repeated File input = 6 [(blox.options.set) = true];
  repeated Param metadata = 7 [(blox.options.set) = true];

  required string impl_archive = 8;
  repeated Status status = 9 [(blox.options.set) = true];
  repeated File output = 10   [(blox.options.set) = true];
}

message JobImpl
{
  required string id = 1;
  required string user_id = 2;
  required string account_id = 3;
  required File file = 4;
  repeated Param metadata = 5 [(blox.options.set) = true];
}


//
// REQUESTS ON JOBS
//

// response is empty
message CreateJobRequest
{
  required string job_id = 1;
  required string client_id = 2;
  required string impl_id = 3;
  required string output_prefix = 4;
  required string user_id = 5;
  repeated File input = 6 [(blox.options.set) = true];
  repeated Param metadata = 7 [(blox.options.set) = true];
}

// response contains Job
message GetJobRequest
{
  required string job_id   = 1;
  optional bool get_metadata = 2;
  optional bool get_status = 3;
  optional bool get_input = 4;
  optional bool get_output = 5;
}

// response is empty
message AddStatusRequest
{
  required string job_id = 1;
  required Status status = 2;
}

// response is empty
message SetResultRequest
{
  required string job_id = 1;
  repeated File output = 2 [(blox.options.set) = true];
}


//
// REQUESTS ON JOB IMPLEMENTATIONS (response contains JobJobImpl messages) 
//

// response is empty
message SetJobImplRequest
{
  required string impl_id = 1;
  required string user_id = 2;
  required File file = 3;
  repeated Param metadata = 4 [(blox.options.set) = true];
}

// response is JobImpl
message GetJobImplRequest
{
  required string user_id = 1;
  optional string impl_id = 2;
}


//
// HELPER MESSAGES
//

message Param
{
  required string key = 1;
  required string value = 2;
}

message File
{
  required string url = 1;
  optional string hash = 2;
}

message Status
{  
  required int64  timestamp = 1;
  required string event     = 2;
  required string machine   = 3;
  required string message   = 4;
}