/**
 * This protocol covers the client-side API to the Steve front-end. It
 * will be used by applications on different versions and for several
 * years, so it needs to be extremely simple and stable. No
 * incompatible changes are allowed on this protocol.
 */
package lb.steve.frontend;

option java_package = "com.logicblox.steve.protocol";

/**
 * Request/response unions
 */
message Request {
  // ask about the state of any asynchronous request
  optional StateRequest state = 2;

  // job
  optional JobCreateRequest create = 1;
  optional JobResultRequest result = 3;
  optional JobCancelRequest cancel = 4;
  optional JobLogRequest log = 5;

  // job implementation request
  optional ImplAddRequest impl_add = 20;
  optional ImplListRequest impl_list = 21;
}

message Response {

  optional string error = 1;
  optional string error_code = 2;

  optional StateResponse state = 11;

  // job
  optional JobCreateResponse create = 10;
  optional JobResultResponse result = 12;
  optional JobCancelResponse cancel = 13;
  optional JobLogResponse log = 14;

  // job implementation
  optional ImplAddResponse impl_add = 20;
  optional ImplListResponse impl_list = 21;
}

/**
 * State
 */
message StateRequest {
  required string id = 1;
  optional bool detail = 2;
}

message StateResponse {
  required State state = 1;
}

/**
 * Create a new job
 */
message JobCreateRequest {
  // Identifier set by the client to make sure that a job is created
  // only once, even when there are networking issues. It turns a
  // create request into an idempotent operation of the job is created
  // more than once.
  required string client_id = 1;

  // Identifier of the job implementation.
  required string job_impl = 2;

  // Metadata on the job.
  //
  // Some keys are reserved:
  // - date           Automatically set when the job is created
  // - timeout        Timeout in seconds
  // - correlation-id Identifier used to correlate executions of
  //                  jobs. The assumption is that jobs executed with
  //                  the same correlation id have similar properties
  //                  in terms of expected execution time.
  // - job-queue      Use a specific job queue (usually to select hardware)
  repeated Param metadata = 3;

  // Parameters to be passed to the execution of the job
  repeated Param input_param = 10;

  // Input files (S3 urls)
  repeated File input = 11;

  // S3 url for output (prefix)
  required string output = 20;
  optional string output_encryption_key = 21;
}

message JobCreateResponse {
  required string job_id = 1;
}

/**
 * Request result of a job execution
 */
message JobResultRequest {
  required string job_id = 1;
}

message JobResultResponse {
  repeated File output = 2;
}


/**
 * Cancel a queued or executing job.
 */
message JobCancelRequest {
  required string job_id = 1;
}

message JobCancelResponse {
  // As a convenience to the client, we return the previous status of
  // the job (the new status will be pending-kill until the kill has
  // been handled)
  required string status = 1; 
}


/**
 * Request log of an executed job.
 */
message JobLogRequest {
  required string job_id = 1;
}

message JobLogResponse {
  required string log = 1;
}


/**
 * Add a new job implementation
 */
message ImplAddRequest {
  // Identifier set by the client to make sure that a job is created
  // only once, even when there are networking issues. It turns a
  // create request into an idempotent operation of the job is created
  // more than once.
  required string client_id = 1;

  // Implementation identifier to be used when submitting jobs for
  // this implementation.
  required string id = 2;

  required File implementation = 3;

  // Defaults to the account of the user.
  optional string account = 4;

  // Metadata on the job.
  //
  // Some keys are resevered:
  // - date  Automatically set when the job implementation is added
  repeated Param metadata = 5;
}

message ImplAddResponse {
  // Identifier for the asynchronous addition of this job
  // implementation.
  required string id = 1;
}

/**
 * List implementations
 */
message ImplListRequest {
}

message ImplListResponse {
  repeated JobImplInfo job_impl = 1;  
}

/**
 * General
 */
message Param {
  required string key = 1;
  required string value = 2;
}

message File {
  required string url = 1;
  optional string hash = 2;
}

message State {
  // Jobs use the following states:
  // - SUCCEEDED
  // - FAILED
  // - UNKNOWN (temporary)
  required string state = 1;
  repeated Status status = 2;
}

message Status {
  required int64 timestamp = 1;
  required string status_code = 2;

  // TODO should we only return the machine under certain
  // authorization conditions?
  optional string machine = 3;

  optional string message = 4;
}

message JobImplInfo {
  required string id = 1;
  repeated Param metadata = 2;
}
