/**
 * This protocol covers the client-side API to the Steve front-end. It
 * will be used by applications on different versions and for several
 * years, so it needs to be extremely simple and stable. No
 * incompatible changes are allowed on this protocol.
 */
package lb.steve.frontend;

option java_package = "com.logicblox.steve.protocol";

/**
 * Request/response unions
 */
message Request {
  optional CreateRequest create = 1;
  optional StatusRequest status = 2;
  optional KillRequest kill = 3;
}

message Response {
  optional string error = 1;
  optional CreateResponse create = 2;
  optional StatusResponse status = 3;
  optional KillResponse kill = 4;
}

/**
 * Create a new job
 */
message CreateRequest {
  // Identifier of the job implementation.
  required string job_impl = 1;

  repeated Param param = 2;

  // S3 urls for input
  repeated File input = 3;

  // S3 url for output (prefix)
  required string output = 4;
  optional string output_encryption_key = 5;

  // Timeout for execution of job
  optional uint64 timeout = 6;
}

message CreateResponse {
  required string job_id = 1;
}

/**
 * Request status of a job
 */
message StatusRequest {
  required string job_id = 1;
}

message StatusResponse {
  required string status = 2;
}

/**
 * Kill a queued or executing job.
 */
message KillRequest {
  required string job_id = 1;
}

message KillResponse {
  // As a convenience to the client, we return the previous status of
  // the job (the new status will be pending-kill until the kill has
  // been handled)
  required string status = 1; 
}

/**
 * General
 */
message Param {
  required string key = 1;
  required string value = 2;
}

message File {
  required string url = 1;
  // TODO support SHA256/512 that we attach ourselves as metadata?
  optional string md5 = 2;
}
