/**
 * This protocol covers the messages sent to and from the Steve key server.
 */
package lb.steve.keys;

option java_package = "com.logicblox.steve.protocol";

message GetKeysRequest {
  required string account = 1;
}

message GetKeysResponse {
  repeated Key keys = 1;
}

message Key {
  required string name = 1;
  required string contents = 2;
}

message RegisterKeyRequest {
  required string account = 1;
  required string name = 2;
  required string contents = 3;
}

message RegisterKeyResponse {
}

