#!/bin/sh

input=$1
output=$2

echo "making database ..."
lb create --overwrite ancestor

echo "adding logic ..."
lb addblock -f ancestor.logic ancestor

echo "adding facts ..."
lb exec -f facts.logic ancestor

echo "printing results ..."
lb print ancestor ancestor > $output/output.txt
