#! /usr/bin/env python
import sys
import boto.ec2
from pprint import pprint

instance_profile_arn = sys.argv[1]

ec2 = boto.ec2.connect_to_region('us-east-1')

instance_ids = []
for i in ec2.get_all_instance_status(filters={'instance-status.status': 'impaired'}, max_results=1000):
    instance_ids.append(i.id)

print "Terminating", instance_ids

if instance_ids != []:
    instances = ec2.get_all_instances(instance_ids, filters={'iam-instance-profile.arn': instance_profile_arn})
    for res in instances:
        res.instances[0].terminate()
